version: '3.8'

services:
  app:
    build: ./api
    container_name: restaurant-os-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/restaurant_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - restaurant-network

  db:
    image: mysql:8.0
    container_name: restaurant-os-db
    ports:
      - "3307:3306" # Map to 3307 to avoid conflict with local MySQL
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=restaurant_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - restaurant-network
    command: --default-authentication-plugin=mysql_native_password

networks:
  restaurant-network:
    driver: bridge

volumes:
  mysql_data:
